### ISSUE TITLE
Frontend - add more buttons

### ISSUE THREAD

**Issue by licaon-kter** [bilde2910/Hauk#101]
eg. On the side under the zoom buttons, some buttons labelled with "UserName"

**Comment by bilde2910** [comment]
Tapping on a user on the map will center the map on that user and automatically pan the map to follow them. I can add a menu that shows the current users on the map as well and add the same functionality for clicking on a user in that menu.

**Comment by licaon-kter** [comment]
> Tapping on a user on the map will center the map on that user 

Yes, but if you don't see the users you need to "zoom out" and then "touch"

**Comment by licaon-kter** [comment]
Frontend - add share location of user button: eg. share a `geo:` link that OsmAnd~ or Google Maps can open and we can "navigate to..." that user or whatever.
(from https://github.com/bilde2910/Hauk/issues/103#issuecomment-564972507)

**Comment by bilde2910** [comment]
There is now a user button in the top left corner that has this functionality. Let me know if you miss anything from it.

**Comment by licaon-kter** [comment]
Look ok, thanks.

**Comment by licaon-kter** [comment]
One note, don't list users that you can't yet see, eg. user was added to the group but they didn't submit a location yet

**Comment by bilde2910** [comment]
Done
