### ISSUE TITLE
Device detection issues

### ISSUE THREAD

**Issue by licaon-kter** [bilde2910/Hauk#104]
Maybe you can add https://dontkillmyapp.com in the pop-up text as "More info:"

How do you detect devices? My Xiaomi is not detected...

**Comment by bilde2910** [comment]
That sounds like a good idea; didn't know that site existed.

>How do you detect devices? My Xiaomi is not detected...

I detect Xiaomi devices by checking [if the device hostname has "-miui-" in it](https://github.com/bilde2910/Hauk/blob/master/android/app/src/main/java/info/varden/hauk/system/powersaving/Device.java#L42-L50). If this doesn't work for you, I'd love it if I could get some data for your device so I can improve the detection. I don't have a Xiaomi device myself, and for those of my friends who have it, apparently you need to sign in with a Xiaomi account to be allowed to install apps via `adb` (which they don't want, for reasonable privacy reasons).

`adb shell getprop | grep ro.build`

**Comment by licaon-kter** [comment]
It's a custom, China based but made global ROM by xiaomi.eu

`[ro.build.host]: [xiaomi.eu]`

**Comment by bilde2910** [comment]
Can you confirm whether this opens the battery savings screen on your device?

`adb shell am start -n "com.miui.powerkeeper/.ui.HiddenAppsContainerManagementActivity"`

**Comment by licaon-kter** [comment]
Yes, it opens one of the Energy management view.

**Comment by bilde2910** [comment]
Thanks for confirming. Hopefully this fixes the issue.
