### ISSUE TITLE
App - add some debug mode

### ISSUE THREAD

**Issue by licaon-kter** [bilde2910/Hauk#106]
Eg. For https://github.com/bilde2910/Hauk/issues/105 I'm not sure where the issue lies, does the app not get the location or is the server at fault, so me seeing the actual location data updating (changing) helps

**Comment by bilde2910** [comment]
Will make sure to add this.

**Comment by bilde2910** [comment]
That should hopefully provide sufficient detail to figure out what's wrong here.
