### ISSUE TITLE
Location not available although link is provided

### ISSUE THREAD

**Issue by bassiecom** [bilde2910/Hauk#109]
installed Hauk today, with memcached as method.
Installed the app on two devices, shared the location and get a sharing link back. But the link keeps saying: 
"Location expired
The shared location you tried to access was not found on the server. If this link worked before, the share might have expired."

Checked the log for accces tot post.php, see the both devices posting ....
xxx.xxx.xxx.xxx - - [15/Dec/2019:16:12:20 +0100] "POST /hauk/api/post.php HTTP/1.1" 200 17 "-" "Hauk/1.5.1 Dalvik/2.1.0 (Linux; U; Android 9; SM-T590 Build/PPR1.180610.011)"
xxx.xxx.xxx.xxx - - [15/Dec/2019:16:12:20 +0100] "POST /hauk/api/post.php HTTP/1.1" 200 17 "-" "Hauk/1.5 Dalvik/2.1.0 (Linux; U; Android 9; Nokia 6.1 Build/PPR1.180610.011)"

Is there an option to debug the sharing link codes in any way?

**Comment by bilde2910** [comment]
Have you checked that the Memcached service is installed and running? (`sudo systemctl status memcached`)

**Comment by bassiecom** [comment]
Yep: 
Version | 3.1.3
-- | --
libmemcached version | 1.0.18
SASL support | yes
Session support | yes

But I haven't SASL configured

**Comment by bilde2910** [comment]
SASL isn't required. But I meant the Memcached daemon, not the PHP extension. Both php-memcached and memcached is required.

`sudo systemctl status memcached` should return something like this:

```
● memcached.service - memcached daemon
     Loaded: loaded (/usr/lib/systemd/system/memcached.service; enabled; vendor preset: disabled)
     Active: active (running) since Sun 2019-12-15 13:05:17 CET; 4h 35min ago
   Main PID: 766 (memcached)
      Tasks: 10 (limit: 19084)
     Memory: 7.9M
     CGroup: /system.slice/memcached.service
             └─766 /usr/bin/memcached -m 64 -c 1024 -l 127.0.0.1,::1 -o modern,drop_privileges

Dec 15 13:05:17 ahkruzvokun systemd[1]: Started memcached daemon.
```

It should state "Active: active (running)"

**Comment by bilde2910** [comment]
@bassiecom Did you figure this out?

**Comment by bilde2910** [comment]
The only fix I can think of for this issue is outlined above. Assuming resolved due to lack of further response.
