### ISSUE TITLE
Unable to find config.php

### ISSUE THREAD

**Issue by jteuber** [bilde2910/Hauk#115]
After a normal install of the current master with the install script on my server in a subdirectory and editing the config file, the companion app shows
 

**Server error**
Unable to find config.php!

I already tried to set the user and group of /etc/hauk/config.php to the same as the files on my webserver, but that didn't help.
Any tips what I'm doing wrong?

**Comment by bilde2910** [comment]
Can you double check that the /etc/hauk directory and /etc are also read-execute accessible by the web server user? I.e. `ls -la /etc/hauk` should show drwxr-x**r-x** for `.` and `..` (i.e. mode 0644).

The config.php file itself can be owned by any user (Hauk does not need write access to it) as long as PHP has permission to read from it.

**Comment by jteuber** [comment]
Yes, the directory is read-executable:

```
$ ls -la /etc/hauk
total 36
drwxr-xr-x   2 web5 client0  4096 Dec 20 19:58 .
drwxr-xr-x 140 root root    12288 Dec 20 17:15 ..
-rw-r--r--   1 web5 client0 12929 Dec 20 17:21 config.php
-rw-r--r--   1 web5 client0   132 Dec 20 17:20 users.htpasswd
```

**Comment by bilde2910** [comment]
That's kind of strange, actually.

Hauk also supports installations with the config file being located in the "include" folder in the web directory. In this case you can just rename "config-sample.php" to "config.php" and use that file instead. Not really sure why /etc/hauk doesn't work in that case. In that case, you could run the install script without `-c`, and it will use the include folder instead (or you can just move it there manually).

**Comment by jteuber** [comment]
Ok, that's interesting. I already tried a symlink in the include folder to the config file in /etc/hauk, but that didn't work either. Just straight up moving it over now did the trick. 
Thanks for the quick help!
