### ISSUE TITLE
Do release a new version

### ISSUE THREAD

**Issue by licaon-kter** [bilde2910/Hauk#116]
...as there are plenty of changes and it looks like I'm the only tester :)

**Comment by bilde2910** [comment]
There are still a handful of things I'd like to clear up, at least #72 and #74. I can tag v1.6 after those are fixed

**Comment by bilde2910** [comment]
All changes that are planned for v1.6 are now implemented. I pushed some new strings to the translation portal regarding LDAP user authentication. I assume you want them translated as well before I tag the release :-)

**Comment by licaon-kter** [comment]
Done ;)

**Comment by bilde2910** [comment]
v1.6 is now [tagged](https://github.com/bilde2910/Hauk/releases/tag/v1.6), rollout to Google Play has been initiated and F-Droid will clone, build and publish the app automatically.
