### ISSUE TITLE
Why is this a selector...

### ISSUE THREAD

**Issue by licaon-kter** [bilde2910/Hauk#118]
...if I only have one option? Or this has more options when I've joined a group share (the case that I have not yet tested)?

![hauknewshare](https://user-images.githubusercontent.com/2282799/71547230-4bfd9f80-2995-11ea-9bf9-be9a0031a663.jpg)

Anyway, if only one option I see no need for a "mode selector".

**Comment by bilde2910** [comment]
You have a point there actually. I'll make sure to remove that menu.

**Comment by licaon-kter** [comment]
Also the text above explains that "this shares only your location" so the mode selector is just duplicated UI

**Comment by bilde2910** [comment]
That's what I just realized. I thought I didn't clarify it. It's admittedly been a while since I've looked at that menu.
