### ISSUE TITLE
Allow sharing more than one day

### ISSUE THREAD

**Issue by licaon-kter** [bilde2910/Hauk#119]
...since now it's limited to 1440 minutes or 24 hours or 1 day.

1.6 self build

**Comment by bilde2910** [comment]
Configurable server-side via [`max_duration`](https://github.com/bilde2910/Hauk/blob/master/backend-php/include/config-sample.php#L241-L242)

**Comment by licaon-kter** [comment]
I'll have to upiate the config indeed. :)
