### ISSUE TITLE
Layout issue with translations

### ISSUE THREAD

**Issue by ploink** [bilde2910/Hauk#127]
Below a screenshot in Dutch (Nederlands) from my phone.  The translation "Toevoegen aan groep toestaan" is long and the column with option values is getting narrow. With my phone it is usable but I saw on a friend's phone with a smaller screen that the space to enter the share duration was like 3 pixels wide or so.  One could fix the translation, but there may be other languages causing the same problem. Word wrapping may be a better solution.

![Screenshot_Hauk_NL](https://user-images.githubusercontent.com/3049492/73611233-0d848180-45e0-11ea-8535-a4c80bac4943.png)

**Comment by ploink** [comment]
I increased the system font size to 120% and then you get this:

![Screenshot_Hauk_NL2](https://user-images.githubusercontent.com/3049492/73637690-2c7b2600-4669-11ea-8fa5-396ef7f5f12e.png)

**Comment by bilde2910** [comment]
Interesting, didn't consider that. I'll make sure to get this patched.

**Comment by bilde2910** [comment]
Sorry for this taking so long to resolve. I've been very busy at uni recently. Fixed now, will include the fix in the next upcoming release.

**Comment by ploink** [comment]
No problem.  Thank you for the fix!

**Comment by bilde2910** [comment]
Release tagged, v1.6.1. May take a few days before it's live everywhere, but at least it's out now.
