### ISSUE TITLE
Bug: Share Link in http not https

### ISSUE THREAD

**Issue by x011** [bilde2910/Hauk#129]
Hi there,
The server is configured on the app as `https://` but the share links  are always in `http://`

**Comment by licaon-kter** [comment]
@x011 on the server, in the config, did you by any chance write `http://` as the URL ?

**Comment by bilde2910** [comment]
As @licaon-kter said, this would be caused by [`public_url`](https://github.com/bilde2910/Hauk/blob/master/backend-php/include/config-sample.php#L278) starting with `http` instead of `https` in the server-side config. Please double check your config and re-open this issue if the problem persists.
