### ISSUE TITLE
Feature request: redis backend

### ISSUE THREAD

**Issue by neonknight** [bilde2910/Hauk#13]
In addition to memcached, how about a redis backend?

**Comment by bilde2910** [comment]
Thanks for the suggestion. I've never worked with Redis before. Is there any specific reason memcached does not work in your case?

**Comment by neonknight** [comment]
I simply prefer redis over memcached :-) and I already use redis for other things, while I only need memcached for hauk. 
On a more objective side, redis has more features than memcached, more data types and can replace it in probably any situation. I'd definitely consider it the more advanced option and way to go in the future. In addition, redis has a geospatial data type which might be handy for applications working with geodata.
However, treat this as a low priority request.

**Comment by bilde2910** [comment]
I see :-) I'll consider it, but it's low priority for now.

**Comment by bilde2910** [comment]
This is now live in the latest backend. The settings are available in the [default configuration file](https://github.com/bilde2910/Hauk/blob/master/backend-php/include/config.php); you can put these settings into your own config file to apply them to your instance.
