### ISSUE TITLE
Return non-200 http code when link share doesn't exist

### ISSUE THREAD

**Issue by sharkusmanch** [bilde2910/Hauk#131]
Is it feasible to make the API return a non-200 response when the requested link does not exist?

This would allow for services like fail2ban to monitor the reverse proxy logs (nginx, etc) and protect against brute force attempts.

**Comment by bilde2910** [comment]
This should be feasible. Viewing invalid links will not return 404 from fetch.php.

**Comment by bilde2910** [comment]
Fixed in upcoming v1.6.1.
