### ISSUE TITLE
Android client app text layout not clear with some screen resolution

### ISSUE THREAD

**Issue by djelloul78** [bilde2910/Hauk#132]
Hello,

I'm currently making tests with this app and I'm impressed by its simplicity and efficiency.

However, I'm using a phone with a screen resolution of 1080*2400 and the text in the main page doesn't show clearly, particularly the space used to set the time duration of our position sharing.
I'll add a screenshot of the situation to make my explanations clear.

It's probably due to the fact that I'm using the app in French language, but do you think something can be done to improve the readability and usage of the main page of the app whatever the language used?

Thank you for your attention.

![IMG_20200324_180715](https://user-images.githubusercontent.com/29686675/77456116-12ed9380-6dfb-11ea-9fdb-65373a2a4a6e.jpg)

**Comment by licaon-kter** [comment]
There were some layout fixes not published yet iirc.

But the main problem is that "Authoriser l'ajout..." string on the left, since everything is indented to that.


Can you try other locales, like English? Does it work better? Gan you edit the string in the translation portal and make it shorter?

**Comment by bilde2910** [comment]
There are indeed some changes that are pushed, but which I forgot to tag as a release. The layout bug (#127) will be fixed the upcoming release. I'll go ahead and publish that shortly before I forget it again.

Upcoming release:

![image](https://user-images.githubusercontent.com/6617815/77457649-416c6e00-6dfd-11ea-9ee1-5d358e525ca1.png)

**Comment by bilde2910** [comment]
Fixed in upcoming v1.6.1. It may take a few days before this is rolled out on all stores.

**Comment by djelloul78** [comment]
Sorry guys for not answering recently on this issue, but I had many things to handle during the national lockdown due to COVID-19...
However, I just wanted to confirm that now the layout is perfectly fitted and there's no problem anymore on the text readability.

Thank you for taking the time to handle this request quickly.
