### ISSUE TITLE
No instructions for updating (server) in README

### ISSUE THREAD

**Issue by uusijani** [bilde2910/Hauk#133]
I presume updating an existing installation is just a matter of replacing the existing files with files from the new release, but as this isn't made explicit in the readme, I'm just a bit apprehensive about going ahead with it.

**Comment by bilde2910** [comment]
This is correct, you can just overwrite the existing install with the new files. I'll see if I can get it added to the README.

**Comment by atonn** [comment]
So I just paste & replace everything but include/config.php, or are there breaking changes and I should manually redo my config each time?

**Comment by bilde2910** [comment]
@atonn It will be safe to upgrade to any newer version within the same major version by simply overwriting the files and keeping the config. There can be new features added that require new config options, but these will default to a predefined value if they're not in the config file. If you want to change from these defaults, then you can add them to your existing config, or manually redo it, either way should work.

If a breaking change takes place that requires manual intervention to the config, the major version will be bumped up (i.e. to 2.x).

**Comment by bilde2910** [comment]
Documentation added. No new updates have been pushed since this issue was made, but I'm planning a new update soon, so it's about time I do something about this. :-)
