### ISSUE TITLE
Issues with LDAP

### ISSUE THREAD

**Issue by nrj5k** [bilde2910/Hauk#142]
Hello 

I recently upgraded from an earlier version to v1.6.1, I was using the HTPASSWD method of authentication. After the upgrade when I try to create a link it says couldn't connect to LDAP server but I am not using LDAP at all and am still on HTPASSWD.

Any idea how I can fix this?

Side note:
Great app, love it and can't stop recommending it.

**Comment by bilde2910** [comment]
That's pretty strange, and shouldn't be happening. There were no changes from v1.6 to v1.6.1 that should have triggered such a bug.

Which version did you upgrade from? And how did you install Hauk? Manually by cloning the repo, using Docker, or from distro repositories/AUR?

**Comment by nrj5k** [comment]
I upgraded from I think 1.4, installed from git manually.

**Comment by nrj5k** [comment]
I got it working now, I think my memcached needed to be updated or recompiled, either way its working. Thank you.

**Comment by mansguiche** [comment]
I have been having this same issue for the past month. As far as I know, no updates to the server or the app have happened in that time. I am using docker-compose from the `bilde2910/hauk` image. I have pulled the latest image just in case but unfortunately it did not fix the issue. Any ideas?

**Comment by mansguiche** [comment]
Found the problem and fixed the error reporting in this pull request https://github.com/bilde2910/Hauk/pull/183 in case anyone else has the same problem. Essentially your htpasswd file is missing or cannot be read but the authentication function doesn't catch for this and tries LDAP instead
