### ISSUE TITLE
Customise Sharing Link

### ISSUE THREAD

**Issue by rustyduffer** [bilde2910/Hauk#144]
Hi,

Is there a way to edit the string that is generated when a user clicks 'Share' ?

By default, mine is always https://example.com/?XXXX-XXXX
But I would like it to be https://CURRENTSERVER/?XXXX-XXXX

(I don't mind if I need to manually tell Hauk what string to output after https:// and before /?XXXX-XXXX, or if it is automatically linked to the server name in the settings).

Apologies if the solution is very obvious - I'm new to setting up webservers and building apps and still learning every day!

**Comment by licaon-kter** [comment]
Edit server name in config...

**Comment by rustyduffer** [comment]
Thanks for the quick reply licaon, I searched the config file for example.com and just changed it to my webserver and it worked perfectly.

Sorry for the silly question! This is literally the first time I've ever set up a webserver (on my Pi) or built / installed software like this.

**Comment by bilde2910** [comment]
You've [forgotten to set](https://github.com/bilde2910/Hauk/wiki/FAQ#why-does-my-shared-location-link-point-to-examplecom) `public_url` in config.php. Make sure you set your domain name there, and it should work again.

**Comment by bilde2910** [comment]
> Thanks for the quick reply licaon, I searched the config file for example.com and just changed it to my webserver and it worked perfectly.
> 
> Sorry for the silly question! This is literally the first time I've ever set up a webserver (on my Pi) or built / installed software like this.

Nice! Good to hear that it works :+1:

Feel free to ask if you have any other questions. :-)
