### ISSUE TITLE
UI bug because of long translations

### ISSUE THREAD

**Issue by cdugeai** [bilde2910/Hauk#145]
The following bug happens when clicking on the button **Create new sharing link**, when the sharing is already active:  

In the french translation (maybe in some others), the translation of "Allow adoption" text label ("Autoriser l'ajout de partage") is so long that we can't see the buttons at the bottom of the pannel.

So we are stuck in front of it, and the android *back key* does not do anything in this situation. We are then forced to *force close* the app to have access to it again.

And we can't scroll in any way to make these buttons come to the screen.

![Screenshot_20200606-174734](https://user-images.githubusercontent.com/46027833/83948558-5a8e9380-a81e-11ea-8f86-5be2dc2b13ed.png)

**Comment by bilde2910** [comment]
Sorry for not getting back to you earlier on this. I've had a lot to do this summer.

A similar issue was raised in #127 but I apparently forgot about this dialog box. Fixed it now, this will be live in the next update. Thanks for reporting!
