### ISSUE TITLE
Two UI Tweaks?

### ISSUE THREAD

**Issue by rustyduffer** [bilde2910/Hauk#146]
Both minor 'issues', but when I launch Hauk the text box for length of time to share location is the active field, which then causes my keyboard to pop up and I have to discard it. Not a big deal, but it's one extra step every single time I launch the app, and I never change this value. Maybe it could be moved to Settings?

If so, and the big 'Hauk' logo is reduced / removed, then the entire UI would fit on my phone screen with no scrolling down to the 'share my location' bit at the bottom. Would look very neat and professional, and the annoying keyboard popup would be solved at the same time!

**Comment by bilde2910** [comment]
> when I launch Hauk the text box for length of time to share location is the active field, which then causes my keyboard to pop up and I have to discard it.

This doesn't happen on my device, but from a quick search on StackOverflow this looks like a common issue on many devices. The fix looks pretty simple too. I'll make sure this is patched in the next release :+1:

> If so, and the big 'Hauk' logo is reduced / removed, then the entire UI would fit on my phone screen with no scrolling down to the 'share my location' bit at the bottom. Would look very neat and professional, and the annoying keyboard popup would be solved at the same time!

I'll look into making the logo display an option in settings that's enabled by default, but can be disabled to hide the logo. This should clean up the UI. Thanks for the suggestion.

**Comment by bilde2910** [comment]
The logo is now toggle-able in settings. It is shown by default, but can be hidden.

As for the keyboard popping up automatically - I can't reproduce this myself, but the fix I implemented seems to be widely suggested. I've closed this now, but if you keep experiencing the issue despite this patch, feel free to repoen.

The changes will be live in the next update.
