### ISSUE TITLE
Handle Expired Sessions Gracefully

### ISSUE THREAD

**Issue by BrookeDot** [bilde2910/Hauk#148]
In 7f21ffb a 404 header was set to fix #131 and more properly handle expired links. When I load an invalid or expired link I see the following JavaScript error:

```
SyntaxError: "JSON.parse: unexpected character at line 1 column 1 of the JSON data"
    onreadystatechange https://example.com/main.js:271
```

This is due to the response not being JSON encoded. But if the string is encoded then the service tries to load the link.

**Comment by bilde2910** [comment]
Checking for 404 would honestly be a better way to check for expired links rather than a JSON syntax error, I agree. Will look into this.

**Comment by bilde2910** [comment]
I've had a lot on my plate and this took way longer than I expected. I'm back now, fix implemented, will be live in next update.
