### ISSUE TITLE
map centering improvement

### ISSUE THREAD

**Issue by alex1702** [bilde2910/Hauk#18]
hi there, I might have an idea for an improvement.. as a viewer, it's annoying that the map always auto center on the target if you want to scroll around on the surroundings.. it would be nice if this feature could be turned on and off... if turned off a button for a manually centering would also be nice.

**Comment by bilde2910** [comment]
Thanks for the suggestion! Have been thinking about this, will definitely implement it.

Additonally bumping this up to high-priority; there are some issues in the latest release that warrants that this is looked into and implemented quickly. Expect this in v1.1.1.

**Comment by bilde2910** [comment]
Suggestion on how this will be implemented:

- When loading a single-user share, the map is centered on, and follows, that user by default.
- When loading a multi-user share, the map is zoomed out from the default enough that all members are visible at the same time, and the map will not follow any one of them by default.
- Clicking on a user on the map will lock the map on that user and follow them around.
- Panning the map will automatically unfollow and allow freely panning the map.

**Comment by bilde2910** [comment]
This is now live; Docker image will be built soon.
