### ISSUE TITLE
Feature request: indicate absence of data in a meaninful way

### ISSUE THREAD

**Issue by RuralYak** [bilde2910/Hauk#19]
Hello, currently if android client waits for gnss fix no data provided to backend and shared location page appears empty. This confuses user. Could you please add some message (e.g."Waiting for location data") on the web page to indicate such state?

Thank you

**Comment by bilde2910** [comment]
That's a good idea. Will try to have this included in the next update :-)

**Comment by bilde2910** [comment]
This is now live; Docker image will be built soon.
