### ISSUE TITLE
initial setup issue

### ISSUE THREAD

**Issue by stanelie** [bilde2910/Hauk#190]
Hello.
Trying to setup a Hauk instance for the first time, I am greeted with a big popup when I try to connect from the Android app : 
"Server error
<?php

//This script handles session
initiation for Hauk clients. It creates
a session
// ID and associated share URL, and
return these to the client.
...
...
..."

Where should I start looking to solve this?

Thanks

**Comment by licaon-kter** [comment]
Which OS? PHP? Steps you took?

**Comment by stanelie** [comment]
ubuntu 20.04, apache, I followed the "manual" installation guide, copying the files from the 2 specified folders to the webroot. I can see the landing page fine.

**Comment by stanelie** [comment]
Never mind, my bad.

**Comment by licaon-kter** [comment]
What was the fix?

**Comment by stanelie** [comment]
<shame> install PHP </shame>
