### ISSUE TITLE
GPS lock already active?

### ISSUE THREAD

**Issue by natrius** [bilde2910/Hauk#2]
Make it possible to see if the GPS lock is there or not. Because, when the lock is there, i can lock my phone and put it back in my pocket and not worry about it anymore.

I have gotten some people who got quite interested in the feature. I will set it up today evening i hope and i will have some users i guess :D

**Comment by bilde2910** [comment]
Good suggestion. When the share is started, I'll have a "Waiting for GPS fix" indicator on the main screen that shows the status of the GPS connection. As soon as the first location is received, it'll update and say "GPS connected" or something similar. I'll try and have it included in the next release.

**Comment by bilde2910** [comment]
This is now included in v1.0.1. I've pushed it to the repo, but I don't know how long it takes for F-Droid to update it - shouldn't be more than a couple of days.
