### ISSUE TITLE
Wrong server name is used

### ISSUE THREAD

**Issue by Dezorian** [bilde2910/Hauk#201]
I've setup my self hosted instance and changed SSL certificates to a different domain name. Sharing the location works but when sharing the old domain name is being used instead of the name that I've setup in the app configuration. I've already rebooten my android phone, reinstalled and removed app cache and data. But still when sharing the old domain name is being used. When I manually change the domain name to the new one, it just works. But the sharing mechanism seems to get a different domain somehow.

**Comment by licaon-kter** [comment]
You've changed this too? https://github.com/bilde2910/Hauk/blob/master/backend-php/include/config-sample.php#L278

**Comment by Dezorian** [comment]
Totally forgot about that. Thanks! Instant fix.
