### ISSUE TITLE
Android sharing url incorrect when using sub-directory

### ISSUE THREAD

**Issue by katchy3132** [bilde2910/Hauk#22]
My server URL is https://hauk.domain.com/hauk/ . 

All works well to update the server. But the "Share tracking link" button in the Android app chops off the /hauk/ directory to 

https://hauk.domain.com/?XXX123-YYY456 

manually  changing the URL in the browser to 

https://hauk.domain.com/hauk/?XXX123-YYY456 

works fine . 

I am using app version 1.0.1

**Comment by katchy3132** [comment]
apparently not. thanks! all is working now.

**Comment by bilde2910** [comment]
Good to hear! Enjoy Hauk :-)
