### ISSUE TITLE
Feature request: Add quick choice for timeouts(1h, 1d etc)

### ISSUE THREAD

**Issue by RuralYak** [bilde2910/Hauk#29]
Hello,

Since ttl for session is defined in minutes it is not convenient to calculate values every time. Is it possible to add predefined time buttons that will populate 1h, 3h, 1d timeouts?

Additionally it would be nice to have an ability to quickly specify maximum possible ttl. 

Thank you.

**Comment by bilde2910** [comment]
I can add a select box next to the input that lets you select between minutes, hours and days. Will that work?

**Comment by RuralYak** [comment]
yup :)

**Comment by bilde2910** [comment]
This will be live in v1.1.1. It may take a couple of days for the app to be available on F-Droid.
