### ISSUE TITLE
Is it safe to block hauk default url ?

### ISSUE THREAD

**Issue by RuralYak** [bilde2910/Hauk#31]
To minimize exposed surface I wanted to block default hauk url that does not have any reference to a particular endpoint document.

Like https://apps.varden.info/demo/hauk/ is blocked 
but https://apps.varden.info/demo/hauk/?2HFB-4KOS allowed

Is that good idea?

**Comment by bilde2910** [comment]
As long as you're careful to only block only the root URL and only if it does not have query string parameters, then that's completely safe. You can do this using nginx as a reverse proxy with e.g.

```nginx
location / {
    proxy_pass http://hauk;
}

location ~* ^/(index.html)?$ {
    if ($args ~ "^$") {
        return 403;
    }
    proxy_pass http://hauk;
}
```

This will return a 403 Forbidden error when you try to access the root, but if you have e.g. `?2HFB-4KOS` at the end, it will allow the connection.

**Comment by RuralYak** [comment]
Think it could be a good suggestion in documentation.

**Comment by bilde2910** [comment]
I can add a section on it in [the FAQ](https://github.com/bilde2910/Hauk/wiki/FAQ).

**Comment by bilde2910** [comment]
Added to FAQ.
