### ISSUE TITLE
Docker container does not react on SIGTERM properly

### ISSUE THREAD

**Issue by RuralYak** [bilde2910/Hauk#32]
Hello there,

Current implementation stuck on stop/kill command and does not pass sigterm signal to running instances of memcache and apache. This results in termination on timeout after 10 seconds. Proper reaction would be passing sigterm to downstream processes:

```
stop_apache()
{
  kill $(cat $apache_pidfile)
  rm -f $apache_pidfile
}

trap stop_apache INT TERM

apache &
echo $! > $apache_pidfile

wait $apache_pidfile
trap - TERM INT
wait $apache_pidfile
```
```
# run  server
CMD ["/bin/bash", "start.sh"]
```

This should result in much more quicker turnover of docker container.

Thank you.

**Comment by bilde2910** [comment]
I did note that it took a while to stop the Hauk container, and it didn't always come back up cleanly. I didn't figure out how to properly handle shutdown, but your PR did fix this issue. Thanks a lot for your contribution!
