### ISSUE TITLE
Unable to load Hauk page on domain [tech support]

### ISSUE THREAD

**Issue by anthonymvicente** [bilde2910/Hauk#35]
Apologies if this isn't the right place to ask, but I'm not sure if you have a support contact anywhere.

I'm currently trying to setup hauk on my domain and running into an issue whenever I visit the page. The page is completely blank, and the console [displays the following errors](https://imgur.com/a/GoSsFNx).

I installed hauk using the install script with `/var/www/find` as my webroot. The files seem to be there. [Here is my nginx configuration](https://pastebin.com/kvjL0PbL).

Please let me know if there's a better place to ask this question or if more info is needed. Thank you.

**Comment by bilde2910** [comment]
That's strange. It looks like the server is sending the wrong content type header for dynamic.js.php for some reason. It [should be `text/javascript`](https://github.com/bilde2910/Hauk/blob/master/backend-php/dynamic.js.php#L7) but looks like it's `text/html` instead.

Can you open the path https://find.example.com/dynamic.js.php directly and see if it contains any errors?

**Comment by anthonymvicente** [comment]
I noticed that too, if I try to go to find.domain.com/dynamic.js.php I get a 404 error from my nginx instance.

**Comment by bilde2910** [comment]
Can you check if *all* the files are in the web root? An expected output would have all of these files:

```sh
user@host /var/www/find $ ls -lA
total 52
drwxr-xr-x 2 root root  4096 Sep 14 16:06 api
drwxr-xr-x 4 root root  4096 Sep 14 16:06 assets
-rw-r--r-- 1 root root   958 Sep 14 16:06 dynamic.js.php
drwxr-xr-x 3 root root  4096 Sep 14 16:06 include
-rw-r--r-- 1 root root  4299 Sep 14 16:06 index.html
-rw-r--r-- 1 root root 19514 Sep 14 16:06 main.js
-rw-r--r-- 1 root root  5812 Sep 14 16:06 style.css
```

**Comment by anthonymvicente** [comment]
It looks right, though some of the sizes don't match exactly. Here's my output:

```
total 40
drwxr-xr-x 1 root root    88 Sep 16 17:52 api
drwxr-xr-x 1 root root   130 Sep 16 17:52 assets
-rw-r--r-- 1 root root   958 Sep 16 17:52 dynamic.js.php
drwxr-xr-x 1 root root    66 Sep 16 17:52 include
-rw-r--r-- 1 root root  4299 Sep 16 17:52 index.html
-rw-r--r-- 1 root root 19566 Sep 16 17:52 main.js
-rw-r--r-- 1 root root  5851 Sep 16 17:52 style.css
```

**Comment by bilde2910** [comment]
I have a slightly older version on my host for main.js, so it does look right to me.

I'm wondering if somehow nginx can't communicate with php-fpm, or if the fpm cannot find the file somehow. This is a bit beyond what I have experience with, but can you check the following:

- Is `php-fpm` actually running?
- Does nginx have permission to read and write to `/var/run/php/php7.2-fpm.sock`?  
E.g. `srwxr-x--- 1 nginx nginx`

I can't see these in your config:

```
fastcgi_param SCRIPT_FILENAME $fastcgi_script_name;
include fastcgi_params;
```

.. but I assume you have those included in your `snippets/fastcgi-php.conf`?

Do other PHP scripts work?

**Comment by bilde2910** [comment]
Actually, scratch that. I believe this might be your problem. Ensure that you have `root /var/www/find;` directly in your `server {}` block instead of within `location /`.

**Comment by anthonymvicente** [comment]
Thanks for the hint, I moved the root property, [here's my new configuration](https://pastebin.com/jUYDUUX5), but still getting the same error. Checked the other things:

yes, php-fpm is running
the permissions for `/var/run/php/php7.2-fpm.sock` are actually www-data if that's an issue?

I've actually never used PHP on my server before, I just installed it for hauk, so I'm not actually sure about the fastcgi_param argument you're talking about... That being said, I setup a quick python page that just echoes phpinfo and it seems to work.

**Comment by bilde2910** [comment]
As long as it's the same user as nginx, it should be fine. On my machine it's `nginx` but `www-data` is also extremely common, so that also looks fine.

The two config lines would go inside your `location ~ \.php` block like so:

```nginx
location ~ \.php$ {
	try_files $uri =404;
	include fastcgi_params;
	fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
	fastcgi_pass unix:/var/run/php/php7.2-fpm.sock;
}
```

If I use that in a simple nginx config, the config below works for me with the settings you provided. Could you try replacing your `location ~ \.php` with the block above and see if that works?

**Comment by anthonymvicente** [comment]
Still no luck, but I'm thinking I haven't properly installed PHP and the memcache setup. I'll need to look into that some more and try again. This can probably be marked as closed, as this definitely isn't an issue with Hauk. Thank you for all the help, I really appreciate your time!

**Comment by bilde2910** [comment]
Sure, no problem! If all else fails, you can also just run the Docker container instead and let that handle everything for you. Your nginx instance could then just be a reverse proxy for TLS termination.

I'll close the issue, but if you need more help, feel free to comment or reopen. Good luck :-)

**Comment by anthonymvicente** [comment]
Well I tried with the docker image and it seems to mostly be working! The only issue I'm running into is that my config didn't seem to take. Am I understanding this correctly, I copy the config.php into my ~/.config/hauk/ directory, then I run the `htpasswd -nBC 10 "" | tail -c +2` command, enter a password when prompted, take the output and place it in the relevant line? Then replace the public url?

**Comment by anthonymvicente** [comment]
Ignore the above, I found what I was doing wrong (incorrect filepath). Thanks again for all the help, this thing is awesome.
