### ISSUE TITLE
Install-script not working completely

### ISSUE THREAD

**Issue by natrius** [bilde2910/Hauk#36]
When trying to install it over an old installation 

```
user@server:~/hauk/Hauk$ sudo ./install.sh -c /var/www/hauk/
./install.sh: 31: [: /var/www/hauk/: unexpected operator
./install.sh: 31: [: /var/www/hauk/: unexpected operator
WARNING! Target directory is not empty. If you proceed with the
installation, all files in the directory will be deleted.
./install.sh: 100: read: Illegal option -e
./install.sh: 101: ./install.sh: [[: not found
Aborting...
```

after moving the folder and reinstalling the followind appears

```
user@server:~/hauk/Hauk$ sudo ./install.sh -c /var/www/hauk/
./install.sh: 31: [: /var/www/hauk/: unexpected operator
./install.sh: 31: [: /var/www/hauk/: unexpected operator
./install.sh: 77: read: Illegal option -e
./install.sh: 78: ./install.sh: [[: not found

-e Installation complete!
Before you use Hauk, make sure to change Hauk's configuration.
The configuration file can be found at:
/etc/hauk/config.php
```

Best regards

**Comment by bilde2910** [comment]
Apparently my shell installation uses bash when I told it not to. This is a bug; I'll work on a fix promptly

**Comment by natrius** [comment]
One further suggestion: 
Mark the "The configuration file can be found at:" as bold because i was to blind to read everything and tried for some minutes to change the config in the /var/www/hauk/include/ folder :)

Reading "Installation cmplete!" going "Yeah!" and not reading more. When someone is installing it the first time, i don't think the mistake will happen.

**Comment by bilde2910** [comment]
Good suggestion. If the `$EDITOR` environment variable is set, the installer will usually also ask if you want to open it for editing. But having it be bold, especially in cases where it doesn't do that, is also useful.

**Comment by bilde2910** [comment]
The changes have been pushed, so you should have a working shell script now if you pull the latest code from the repo.
