### ISSUE TITLE
Android: share link with clipboard option

### ISSUE THREAD

**Issue by Somebodyisnobody** [bilde2910/Hauk#38]
Hello, I have the option to copy the video address in YouTube. (Share -> [Share Dialog appears] -> "Copy Link"). That would be an useful enhancement for the android app.

**Comment by bilde2910** [comment]
This is already possible, but might depend on your phone. Using the share option, you can share to the "Copy to clipboard" receiver. Alternatively, you can use the "Copy link" button from the Hauk notification to copy to clipboard directly.

If you don't have a "Copy to clipboard" option on the share menu, there are some apps that offer the same functionality. [This one](https://github.com/tengusw/share_to_clipboard) is open source and while I haven't personally tried it, it looks like it might be exactly what you're looking for.

![Screenshots](https://user-images.githubusercontent.com/6617815/65377902-80d0cb00-dcb1-11e9-8941-ace1652318d4.png)
