### ISSUE TITLE
Rename  config.php to config-sample.php

### ISSUE THREAD

**Issue by BrookeDot** [bilde2910/Hauk#39]
As the `includes/config.php` needs to be modified for each install should this file be renamed to something like `config-sample.php`? This would allow Hauk to check if `config.php` is found before trying to load and gracefully fail. It has the added advantage of making upgrades easier preventing the config file from being overwritten by a new version.

**Comment by bilde2910** [comment]
Hauk will prefer reading the config file from /etc/hauk/config.php if available. This isn't documented that well. But moving the config to config-sample.php sounds like a good idea as well.

**Comment by BrookeDot** [comment]
> Hauk will prefer reading the config file from /etc/hauk/config.php

Ah neat, I missed that.
https://github.com/bilde2910/Hauk/blob/master/backend-php/include/inc.php#L82
