### ISSUE TITLE
Save password

### ISSUE THREAD

**Issue by natrius** [bilde2910/Hauk#4]
Most people will stick to one server, i guess. Make it at least optional to save the password with a checkbox or something like that. 

Works like a charm btw. (non-docker installation)

**Comment by bilde2910** [comment]
Will make sure this makes it in the next release :-)

**Comment by bilde2910** [comment]
This is now included in v1.0.1. I've pushed it to the repo, but I don't know how long it takes for F-Droid to update it - shouldn't be more than a couple of days.
