### ISSUE TITLE
Check for document.getElementById in main.js

### ISSUE THREAD

**Issue by BrookeDot** [bilde2910/Hauk#40]
I use a slightly modified `index.html` page which includes my custom CSS styles and text changes. With the most recent update I ran into an issue with the [`index` template](https://github.com/bilde2910/Hauk/blob/master/frontend/index.html#L69) where `#url` was undefined causing a fatal JavaScript error. 

I tracked this down to `document.getElementById("url").textContent = url;` in `main.js`
https://github.com/bilde2910/Hauk/blob/master/frontend/main.js#L215

To keep things simple and to not make changes to `main.js` I just set the color of the `URL` div to match the background color which works. I think I could also use `visibility:hidden` instead

Overall,  I do like the new changes providing more information but wondering if we should wrap some of the `getElementById` statements in a `if type !== undefined)` checks. If so, which ones? 

The main one the effects the layout I've found is `#URL` so that's why I'm specifically mentioning that one.

**Comment by BrookeDot** [comment]
Default view:
<img width="992" alt="Screen Shot 2019-10-02 at 5 54 37 PM" src="https://user-images.githubusercontent.com/150348/66091712-c3aa6280-e53d-11e9-9a5d-b0ea64d9f96f.png">

Showing the URL is still there but hidden:
<img width="843" alt="Screen Shot 2019-10-02 at 5 57 04 PM" src="https://user-images.githubusercontent.com/150348/66091803-11bf6600-e53e-11e9-822c-24004a30265d.png">

**Comment by bilde2910** [comment]
I can certainly implement this, as it's a pretty quick fix. Maybe it could be an idea to allow some kind of custom HTML setup, but right now I have no idea whatsoever on how to practically implement that.

**Comment by bilde2910** [comment]
Fixed in latest commit. Modifying the HTML isn't really officially supported, but at least you shouldn't get errors anymore when doing it
