### ISSUE TITLE
Only load tiles on valid share URL

### ISSUE THREAD

**Issue by BrookeDot** [bilde2910/Hauk#41]
Currently when you load the app without a valid ID it loads `leafly.js` and "tiles" from the map provider (in my case a single page load uses 32 tiles from Thunderforest). As many providers, such as Thunderforest bill per "tile" it would be ideal to not load any tiles unless a map is actually being displayed.

**Comment by bilde2910** [comment]
I will look into this and see if I can resolve it. I'm currently doing a massive refactor of the entire Android code, so it may take a little while before I can get to it, but I'll definitely get it done.

**Comment by bilde2910** [comment]
Sorry for this taking a bit longer than anticipated. Fixed in latest commit :-)
