### ISSUE TITLE
Server error: java.nio.charset.CharsetICU[UTF-8] on android app

### ISSUE THREAD

**Issue by Chewie9999** [bilde2910/Hauk#45]
I have followed the manual install instructions, and I get the error on my Fairphone 2, running Android 6.0.1.
Do you know what I need to check?
I can't see any errors in my Apache access or error logs, which makes me feel it's not even trying to connect to my server URL.

**Comment by bilde2910** [comment]
Hopefully this resolves it. The update should be live in a few days. Thanks for reporting!

**Comment by Chewie9999** [comment]
Thanks @bilde2910 ! I will look out for it and test again.
