### ISSUE TITLE
French translation in progress :)

### ISSUE THREAD

**Issue by thifranc** [bilde2910/Hauk#48]
Added translation for Web frontend and Android client so far

**Comment by bilde2910** [comment]
Thanks a lot for your help, I really appreciate it! I just pushed out v1.3 yesterday, but I'll make sure your translation is included in v1.3.1 when you're done :-)

**Comment by thifranc** [comment]
Done a new pass on it today :)

**Comment by bilde2910** [comment]
Thanks! I'll close this issue for now, thanks a lot for your contributions! It'll be live in the next update.
