### ISSUE TITLE
Getting 404 error for dynamic.js.php when trying to log in from App

### ISSUE THREAD

**Issue by Chewie9999** [bilde2910/Hauk#49]
Thanks for fixing #45!
I'm afraid I now have another error.
It complains of a 404 when trying to log in.
Looking at my server logs, my client is trying to load dynamic.js.php from the /frontend/ directory.
In /frontend/index.html, it references "./dynamic.js.php", but this file is in the /backend-php/ directory.
Should I copy/move the file, or change index.html?

Thanks,

**Comment by bilde2910** [comment]
Hi! The frontend and backend-php folders should be merged when you copy them to your web root as per the [installation instructions](https://github.com/bilde2910/Hauk#manual-installation). That means that dynamic.js.php should indeed be alongside index.html and the other files, along with everything else in the backend folder. :-)

**Comment by Chewie9999** [comment]
Ah, sorry, I misunderstood that part, thank you :)
