### ISSUE TITLE
Show how much time is left (app and browser)

### ISSUE THREAD

**Issue by natrius** [bilde2910/Hauk#5]
There is right now a notification when the location-sharing-time expires, but add a Timer on how much minutes are left, for example. No need to be over-detailed (seconds) in my opinion, but sometimes useful.

In the app itself so i can see how much time is left and/or on the map for the viewer.

**Comment by bilde2910** [comment]
Good idea. I've implemented it; it will be part of the next release.

**Comment by bilde2910** [comment]
This is now included in v1.0.1. I've pushed it to the repo, but I don't know how long it takes for F-Droid to update it - shouldn't be more than a couple of days.
