### ISSUE TITLE
The Android app icon is smallish

### ISSUE THREAD

**Issue by licaon-kter** [bilde2910/Hauk#52]
...in all launchers except those based on the Google Pixel one.

Eg. For these https://search.f-droid.org/?q=launcher&page=1&lang=en only Rootless Pixel Launcher and Lawnchair have it full size, all the others (KISS, BlissLauncher, Essential Launcher, Simple App Launcher, etc) show it at 25% or thereabout

![Screenshot_2019-10-29-10-18-25-193_com simplemobiletools applauncher](https://user-images.githubusercontent.com/2282799/67750133-7fb85980-fa26-11e9-8211-caa469a2fdc5.jpg)

**Comment by bilde2910** [comment]
Thanks for reporting. I have an idea of how to resolve this. I don't think I'll be able to push the fix until v1.3.2 because of an ongoing RMA with my equipment, but once everything is in order again I'll make sure to patch this, test it and push it out.

**Comment by bilde2910** [comment]
I believe I have a fix ready for this now. It will be in v1.3.1 which will be pushed out shortly. It may take a few days for the app to update in F-Droid.

**Comment by licaon-kter** [comment]
Please reopen, not fixed in 1.3.1

**Comment by bilde2910** [comment]
Can you try reinstalling the app and see if that fixes it first? I'm unable to reproduce somehow

**Comment by licaon-kter** [comment]
Already did.

Some more info, it looks ok in KISS on Android 6.0.1 but still small in KISS on Android 10.

**Comment by bilde2910** [comment]
I'll have to look into that. I verified that it works on Android 6, but I don't have any Android 10 compatible devices to test with. I'll see if I can get a VM up and running and then I'll see if I can reproduce it.

**Comment by bilde2910** [comment]
Unable to reproduce on KISS Launcher on Android Q emulator

![image](https://user-images.githubusercontent.com/6617815/68551245-26c7c880-040b-11ea-867e-c458f12f6e74.png)

**Comment by licaon-kter** [comment]
Appears better in 1.5

Thanks

**Comment by bilde2910** [comment]
That's strange, I didn't actually touch the icon in 1.5. But good to hear that it works now :-)

**Comment by licaon-kter** [comment]
Yeah, it's not the same size, maybe more like twice as big, compared to the pic above.
