### ISSUE TITLE
Create Russian and Ukrainian translations for project

### ISSUE THREAD

**Issue by RuralYak** [bilde2910/Hauk#53]
Dear @bilde2910, please create Russian and Ukrainian translations for Hauk here https://traduki.varden.info/projects/hauk/#languages

**Comment by bilde2910** [comment]
Hi @RuralYak! You can start translations from within each component yourself by going to the [components overview](https://traduki.varden.info/projects/hauk/). Navigate into each component and you'll see a "Start new translation" button underneath the list of languages. You have to sign in before this button appears.

There are three components, the Android client (~80% of the total text volume), the PHP backend and the web frontend (about 10% each).

Thanks for willing to help out with translations! :-)

**Comment by RuralYak** [comment]
Please update README.md. It instructs to call for help in case one need new localization.

**Comment by bilde2910** [comment]
Huh, I thought I fixed it earlier, but apparently forgot. Thanks for pointing that out :-)

**Comment by RuralYak** [comment]
Some of the labels can not be translated correctly due to size limitation. For instance size of  label_allow_adopt limited to 150 char, which leave no chances for appropriate translation

label_allow_adopt
![Screenshot_20191105_124236](https://user-images.githubusercontent.com/25221496/68244720-42297280-ffca-11e9-90f3-2d0ccf213316.png)

**Comment by bilde2910** [comment]
The string you appear to be translating is the additional context, which is there to provide context to the string that should be translated. The string to translate is the one below it, the "source"

**Comment by RuralYak** [comment]
Damn, you're right :)

**Comment by bilde2910** [comment]
That is, the context is there to help you as a translator and won't be displayed in the app :-)

**Comment by RuralYak** [comment]
done

**Comment by bilde2910** [comment]
Thanks a lot for your contributions! Your translations will be live in v1.3.2.
