### ISSUE TITLE
Feature request: User accounts instead of one server password

### ISSUE THREAD

**Issue by zimbelstern** [bilde2910/Hauk#54]
As I would like to let several people use my server for location sharing, user accounts with separate password would come in handy. Consider the following advantages:
- Better security: no need to change the server's password if a user leaks the password or if the permission for a user to use the server is revoked
- Better compatibility: user accounts could be connected to other services (e.g. prosody in my case) with a single password per user for all services
---
Off topic:
Thank you so much for the development of this app and server! I had virtually been trying every location sharing app on F-Droid, most of them didn't work, were bloated, or I couldn't manage to setup the server. I was about to write my own application when I finally found Hauk!

**Comment by bilde2910** [comment]
Hi! Really good to hear that Hauk works well for you :-)

There was some discussion a while ago about adding user authentication support, but I didn't do more about it then, as I assumed that instances would be small enough that the password would only be shared with trusted individuals. That said, you do provide some valid arguments for user authentication, and I'll see what I can do about it.

I have several options on how to implement authentication. The simplest case would be a static .htpasswd-file-based approach where users are added to a file, but that doesn't integrate well. I can also add a RADIUS- and/or LDAP-based alternative authentication flow. Aside from that, do you have any suggestions or preferences of authentication protocols that could be implemented into Hauk? I don't know what works well with existing solutions.

**Comment by zimbelstern** [comment]
Great to hear that my request is regarded! :-) It's not that I don't trust my users' secrecy. But you have to trust their phones and the way of communication with them, too.

I am familiar with the htpasswd-based approach because the CalDAV and CardDAV server radicale is using it but as I don't have any experiences with RADIUS or LDAP, I guess I am the wrong person to ask.

In my case, with only a handful of personally known users and focusing mainly on the XMPP service, my setup is still small enough to handle the accounts for each service manually. But as I am planning to extend my portfolio of free and privacy-friendly services, I will probably have to look into central user management tools one day.

**Comment by bilde2910** [comment]
I'll start off with htpasswd then. It's the easiest to implement by far.

**Comment by bilde2910** [comment]
This will be live in v1.4.
