### ISSUE TITLE
Unable to use own CA

### ISSUE THREAD

**Issue by Mondei1** [bilde2910/Hauk#55]
I saw that support has been added for user CAs in version 1.1.1 (issue #26) but I'm not able to make use of it. Maybe it's my fault but this is my situation:

I created my own root CA, copied it to my phone and installed it. Before I installed it, I got this error: `java.security.cert.CertPathValidatorException: Trust anchor for certification path not found`. After I added my CA I got this: `Hostname 192.168.xxx.xxx not verified: certificate: sha1/xxxxxxxxxx DN: CN=192.168.xxx.xxx,O=None ...`

So he doesn't trust it completely. Did I missed something? Is it the certificate which is wrong or something? Can I only use certificates on domains or is it possible to also use IP-addresses?

**Comment by bilde2910** [comment]
Thanks for the report. Can you check if accessing your site with Chrome on the same phone works? Also, could you take a screenshot of your error message? (With sensitive information redacted/blacked out.)

However, self-signed CAs should generally be a last resort only. Have you tried using Let's Encrypt to get a certificate?

**Comment by Mondei1** [comment]
*(Screenshots are below. Note that blue text is translated from German to English)*

I haven't created my CA with Let's Encrypt. My goal is to access Hauk via VPN on my raspberry pi 3. Since you can't create Let's Encrypt CAs for plain IP-addresses I was forced to create my own CA. But I kinda solved this problem now because I use my own public server for this which has a valid Let's Encrypt certificate and a domain.

I have another question, which is maybe a little bit off-topic: Can I increase the amount of random letters for the location id? So instead of having something like 36YT-A2SQ having XXXXXXXX-XXXXXXXX.

![Screenshot_20191112-162112](https://user-images.githubusercontent.com/22984849/68684793-fb56f200-0560-11ea-945c-eb4b7fec4182.png)
![Screenshot_20191112-153040](https://user-images.githubusercontent.com/22984849/68684794-fbef8880-0560-11ea-8dac-dabf54f290dc.png)

**Comment by bilde2910** [comment]
It looks like the certificate you have on your pi is issued to `mypi.local` and not `192.168.x.x`. The distinguished name (DN) in the certificate has to match the domain name/IP address exactly - just having the same IP isn't enough. So when you create the certificate, you have to enter `192.168.x.x` instead of `mypi.local`. An alternative is to add the IP address `192.168.x.x` to the subject alternate name (SAN) field of the certificate.

**Comment by bilde2910** [comment]
As for the length of the ID in the URL - eight characters offers 36<sup>8</sup> unique combinations - that is 2.8 trillion different combinations (2.8 × 10<sup>12</sup>) of URLs. It shouldn't be possible to feasibly brute force that big of a key space. If you were able to try 1000 different URLs every second, it would take around 45 years on average to discover your URL (assuming you are sharing your location 24/7 for that long). Is there any particular reason you want more characters? I'd be happy to accommodate, but I just don't see what kind of actual benefit you'll get.

For reference, Glympse currently uses either 6 or 8 characters for their public service.

**Comment by Mondei1** [comment]
> It looks like the certificate you have on your pi is issued to `mypi.local` and not `192.168.x.x`. The distinguished name (DN) in the certificate has to match the domain name/IP address exactly - just having the same IP isn't enough. So when you create the certificate, you have to enter `192.168.x.x` instead of `mypi.local`. An alternative is to add the IP address `192.168.x.x` to the subject alternate name (SAN) field of the certificate.

Now I changed the DN to the IP of my pi and I get the same error. Somehow I can't make use of my `mypi.local` domain on my phone, which is weird because I use the same DNS as my computer. I go with my server which has a valid certificate and domain.

**Comment by Mondei1** [comment]
> As for the length of the ID in the URL - eight characters offers 368 unique combinations - that is 2.8 trillion different combinations (2.8 × 1012) of URLs. It shouldn't be possible to feasibly brute force that big of a key space. If you were able to try 1000 different URLs every second, it would take around 45 years on average to discover your URL (assuming you are sharing your location 24/7 for that long). Is there any particular reason you want more characters? I'd be happy to accommodate, but I just don't see what kind of actual benefit you'll get.
> 
> For reference, Glympse currently uses either 6 or 8 characters for their public service.

You're right, makes sense now. No, I don't see any advantage, I was just curious. I just had an idea: The best thing would be to setup Fail2Ban to prevent brute-forcing. 

Since my issue is "resolved" I can now close this issue. I think it was just an error of my own with this certificate.

**Comment by bilde2910** [comment]
You can change the link ID now; see #73
