### ISSUE TITLE
Links generated from the app are "Location expired"

### ISSUE THREAD

**Issue by POTOFGREED** [bilde2910/Hauk#57]
I have manually installed the server and configured the config.php and when i share location from the app it gives me link but when i go to the link it says:

"Location expired
The shared location you tried to access was not found on the server. If this link worked before, the share might have expired."

I have tried many times to get it working by changing settings in the config.php but its all the same result.
Also dark theme on the android app would be much appreciated 😄

**Comment by POTOFGREED** [comment]
I tried with the demo server and it works but not mine :(

**Comment by POTOFGREED** [comment]
After trying 1.3.1 server i still get the same problem

**Comment by POTOFGREED** [comment]
here is my php config with the domain name edited and password 
[config.php.txt](https://github.com/bilde2910/Hauk/files/3856342/config.php.txt)

**Comment by bilde2910** [comment]
It seems you've set the `memcached_host` to "https://your.domain". The `memcached_host` setting should be the host that `memcached` is running on. If you installed `memcached` is installed on the same server, the address should be "localhost" as in the default config (without any "http" or "https" in front).

**Comment by POTOFGREED** [comment]
Changed it to localhost and still the same problem, i will contact the hosting providers about memcached if that is the root of the problem

**Comment by bilde2910** [comment]
Have you installed memcached on the server?

**Comment by POTOFGREED** [comment]
Ok it looks like the hosting provider had to install memcached for me and now it works perfectly

**Comment by bilde2910** [comment]
Good to hear you got it resolved :-) Closing
