### ISSUE TITLE
Docker container doesn't restart

### ISSUE THREAD

**Issue by krystiancha** [bilde2910/Hauk#59]
I'm running Hauk with Docker on a Raspberry Pi 4 B. When i create a container and run it, Hauk works fine, but when the container is stopped and then started again, it exits with an error.

```text
hauk_1      | Started
hauk_1      | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.18.0.5. Set the 'ServerName' directive globally to suppress this message
hauk_1      | httpd (pid 18) already running
```

Recreating the container fixes the problem, but should not be required.

If there is any additional information I can provide to help, let me know.

**Comment by bilde2910** [comment]
That's strange. An earlier patch should have fixed this issue. How are you building and running the container, and how do you stop it?

**Comment by krystiancha** [comment]
Thanks for the reply. I don't fully understand how, because I tried it before, but rebuilding the image from master fixed the issue. Sorry for wasting your time.

**Comment by bilde2910** [comment]
No problem. I have a couple of pis (3 and 3B) that I could test on, but it didn't make sense to me so I figured I'd ask first. Glad it works for you now! Feel free to reopen if it happens again

**Comment by Myzel394** [comment]
I'm also suddenly facing this issue (using Docker) - is there some way to set `ServerName` using environmental variables?
