### ISSUE TITLE
The server returned an empty response

### ISSUE THREAD

**Issue by licaon-kter** [bilde2910/Hauk#64]
nginx, php7.3, redis5, debian, arm64

`curl -X POST https://domain.tld/api/create.php -F pwd="mypassword" -F dur=10 -F int=1 -D - 2>/dev/null | sed -e 's/domain.tld/redacted-hostname/g' | hexdump -C` says:
```
00000000  48 54 54 50 2f 32 20 32  30 30 20 0d 0a 73 65 72  |HTTP/2 200 ..ser|
00000010  76 65 72 3a 20 6e 67 69  6e 78 0d 0a 64 61 74 65  |ver: nginx..date|
00000020  3a 20 53 61 74 2c 20 30  37 20 44 65 63 20 32 30  |: Sat, 07 Dec 20|
00000030  31 39 20 30 30 3a 34 34  3a 34 31 20 47 4d 54 0d  |19 00:44:41 GMT.|
00000040  0a 63 6f 6e 74 65 6e 74  2d 74 79 70 65 3a 20 74  |.content-type: t|
00000050  65 78 74 2f 68 74 6d 6c  3b 20 63 68 61 72 73 65  |ext/html; charse|
00000060  74 3d 55 54 46 2d 38 0d  0a 0d 0a                 |t=UTF-8....|
0000006b
```

nginx access log:
`"POST /api/create.php HTTP/1.1" 200 31 "-" "Hauk/1.5 Dalvik/2.1.0 (Linux; U; Android X.X; Device info)" "-"`

Logcat on Android says:
```
E info.varden.hauk.ui.DialogPacketFailureHandler.onFailure(DialogPacketFailureHandler.java:57): Packet was not properly handled by the client or server
E info.varden.hauk.ui.DialogPacketFailureHandler.onFailure(DialogPacketFailureHandler.java:57): info.varden.hauk.http.ServerException: The server returned an empty response.
E info.varden.hauk.ui.DialogPacketFailureHandler.onFailure(DialogPacketFailureHandler.java:57):  at info.varden.hauk.http.SessionInitiationPacket.onSuccess(SessionInitiationPacket.java:134)
E info.varden.hauk.ui.DialogPacketFailureHandler.onFailure(DialogPacketFailureHandler.java:57):  at info.varden.hauk.http.Packet$1.run(Packet.java:89)
E info.varden.hauk.ui.DialogPacketFailureHandler.onFailure(DialogPacketFailureHandler.java:57):  at info.varden.hauk.http.ConnectionThread.onPostExecute(ConnectionThread.java:114)
E info.varden.hauk.ui.DialogPacketFailureHandler.onFailure(DialogPacketFailureHandler.java:57):  at info.varden.hauk.http.ConnectionThread.onPostExecute(ConnectionThread.java:31)
E info.varden.hauk.ui.DialogPacketFailureHandler.onFailure(DialogPacketFailureHandler.java:57):  at android.os.AsyncTask.finish(Unknown Source:10)
E info.varden.hauk.ui.DialogPacketFailureHandler.onFailure(DialogPacketFailureHandler.java:57):  at android.os.AsyncTask.access$900(Unknown Source:0)
E info.varden.hauk.ui.DialogPacketFailureHandler.onFailure(DialogPacketFailureHandler.java:57):  at android.os.AsyncTask$InternalHandler.handleMessage(Unknown Source:28)
E info.varden.hauk.ui.DialogPacketFailureHandler.onFailure(DialogPacketFailureHandler.java:57):  at android.os.Handler.dispatchMessage(Unknown Source:19)
E info.varden.hauk.ui.DialogPacketFailureHandler.onFailure(DialogPacketFailureHandler.java:57):  at android.os.Looper.loop(Unknown Source:242)
E info.varden.hauk.ui.DialogPacketFailureHandler.onFailure(DialogPacketFailureHandler.java:57):  at android.app.ActivityThread.main(Unknown Source:98)
E info.varden.hauk.ui.DialogPacketFailureHandler.onFailure(DialogPacketFailureHandler.java:57):  at java.lang.reflect.Method.invoke(Native Method)
E info.varden.hauk.ui.DialogPacketFailureHandler.onFailure(DialogPacketFailureHandler.java:57):  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
E info.varden.hauk.ui.DialogPacketFailureHandler.onFailure(DialogPacketFailureHandler.java:57):  at com.android.internal.os.ZygoteInit.main(Unknown Source:275)
V info.varden.hauk.dialog.DialogService.showDialog(DialogService.java:78): Showing dialog with title=Server error, message=The server returned an empty response., run=info.varden.hauk.ui.MainActivity$ResetTask@e0706c6
````
`sudo netstat -tupan | grep LISTEN` says:
```
tcp        0      0 127.0.0.1:8445          0.0.0.0:*               LISTEN      21661/php-fpm: mast
tcp        0      0 127.0.0.1:6379          0.0.0.0:*               LISTEN      19846/redis-server
```

What am I missing? Where is the log of the response? Which app fails: nginx, php, fpm, redis?

**Comment by bilde2910** [comment]
First of all, thanks for an extremely detailed report!

From what you provided, it looks like some part of PHP or the connection between nginx and php-fpm is broken. I installed nginx, php-fpm and redis on my Raspberry Pi to try and reproduce the issue on armhf. It doesn't happen on the default configs, but I did some digging around the logs myself and found a small notice-level error in nginx's error.log. Normally this wouldn't be enough to cause PHP to break this way, but looking at the headers provided in your hexdump, you seem to be running more hardened configs than default. My guess is that PHP treats this error as fatal for some reason (which I've seen happen in certain configurations). I patched this in the above commit - could you try pulling the latest version of that file and see if the error persists?

If not, could you see if there's anything suspicious going on in /var/log/nginx/error.log or /var/log/php7.3-fpm.log?

**Comment by licaon-kter** [comment]
Ok, updated to HEAD, now it says it got error 405
> **405 Method Not Allowed**
    A request method is not supported for the requested resource; for example, a GET request on a form that requires data to be presented via POST, or a PUT request on a read-only resource.

No errors in: nginx/logs, redis/logs or php7.3-fpm.log :(

**Comment by bilde2910** [comment]
At least the initial error seems to be gone. Hauk itself doesn't generate 405's, so this must be some configuration in nginx. What does your nginx config look like for Hauk, and how are you connecting nginx with php-fpm/handing off requests to php-fpm in the nginx config?

Can you also provide a new hexdump?

`curl -X POST https://domain.tld/api/create.php -F pwd="mypassword" -F dur=10 -F int=1 -D - 2>/dev/null | sed -e 's/domain.tld/redacted-hostname/g' | hexdump -C`

**Comment by licaon-kter** [comment]
Ok, looks like I've messed up some stuff, that 405 might be human error on my part, commented some nginx php stuff out when testing.

So we are back at empty response, my config:

nginx/sites/hauk
```
server {
    listen 443;
    listen [::]:443;
    server_name hauk.domain.tld
    root /var/www/hauk;
    error_log /var/log/nginx/hauk.convorb.im_error.log error;
    access_log /var/log/nginx/hauk.convorb.im_access.log main;
    location ~ [^/]\.php(/|$) {
        fastcgi_split_path_info ^(.+?\.php)(/.*)$;
        if (!-f $document_root$fastcgi_script_name) {
                return 404;
            }
            fastcgi_param HTTP_PROXY "";
            fastcgi_pass unix:/run/php/php7.3-fpm.sock;
#           fastcgi_pass 127.0.0.1:8445 #same error
            fastcgi_index index.php;
            include fastcgi_params;
    }
    include /etc/nginx/domain.tld/ssl-common.conf;
}
```

No redis config change, no php-fpm change (except ip or socket selection)

**Comment by licaon-kter** [comment]
Ok, looks like I've messed up some stuff, that 405 might be human error on my part, commented some nginx php stuff out when testing.

So we are back at empty response, my config:

nginx/sites/hauk
```
server {
    listen 443;
    listen [::]:443;
    server_name hauk.domain.tld
    root /var/www/hauk;
    error_log /var/log/nginx/hauk.domain.tld_error.log error;
    access_log /var/log/nginx/hauk.domain.tld_access.log main;
    location ~ [^/]\.php(/|$) {
        fastcgi_split_path_info ^(.+?\.php)(/.*)$;
        if (!-f $document_root$fastcgi_script_name) {
                return 404;
            }
            fastcgi_param HTTP_PROXY "";
            fastcgi_pass unix:/run/php/php7.3-fpm.sock;
#           fastcgi_pass 127.0.0.1:8445 #same error
            fastcgi_index index.php;
            include fastcgi_params;
    }
    include /etc/nginx/domain.tld/ssl-common.conf;
}
```

No redis config change, no php-fpm change (except ip or socket selection)

curl
```
00000000  48 54 54 50 2f 32 20 32  30 30 20 0d 0a 73 65 72  |HTTP/2 200 ..ser|
00000010  76 65 72 3a 20 6e 67 69  6e 78 0d 0a 64 61 74 65  |ver: nginx..date|
00000020  3a 20 53 61 74 2c 20 30  37 20 44 65 63 20 32 30  |: Sat, 07 Dec 20|
00000030  31 39 20 32 33 3a 30 33  3a 35 32 20 47 4d 54 0d  |19 23:03:52 GMT.|
00000040  0a 63 6f 6e 74 65 6e 74  2d 74 79 70 65 3a 20 74  |.content-type: t|
00000050  65 78 74 2f 68 74 6d 6c  3b 20 63 68 61 72 73 65  |ext/html; charse|
00000060  74 3d 55 54 46 2d 38 0d  0a 0d 0a                 |t=UTF-8....|
0000006b
```

**Comment by bilde2910** [comment]
Can you try to add this to your `location` block?

```nginx
fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
```

FWIW, this is my bare-bones nginx config for PHP:

```nginx
location ~ \.php$ {
    try_files $uri =404;
    fastcgi_pass 127.0.0.1:9000;
    include fastcgi_params;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    fastcgi_hide_header X-Powered-By;
}
```

**Comment by licaon-kter** [comment]
Yup, I figured the same while reading https://www.nginx.com/resources/wiki/start/topics/examples/phpfcgi/ again

`Please note if you’re using Ubuntu Precise (12.04), I change SCRIPT_FILENAME and add PATH_INFO params.` 

Albeit I've seen the warning before, I've missed that Debian (at least buster here on arm64) doesn't have it in `fastcgi_params`.

**Comment by bilde2910** [comment]
Yeah, I don't really know why `SCRIPT_FILENAME` is not included, but I usually have to add it separately for that reason.

Good to hear it works now, though. Feel free to let me know if you encounter any more issues :-)
