### ISSUE TITLE
docker for raspberrypi

### ISSUE THREAD

**Issue by ashjas** [bilde2910/Hauk#65]
Please consider creating a docker image for raspberrypi.

**Comment by bilde2910** [comment]
It's currently possible to build the Docker image manually for arm32v7/armhf, but the Docker Hub image is amd64 only and that's not ideal. I'll see if I can somehow configure the automated Docker Hub builds to build multiarch images. This should add support for the official image for Raspberry Pi as well.

**Comment by bilde2910** [comment]
Finally after a lot of failing builds, I've managed to set up the `bilde2910/hauk:latest` tag as multiarch. The Docker Hub image is now built for the following architectures:

- `amd64` - standard x86_64 servers, built natively
- `arm32v7`/`arm/v7` - 32-bit ARM (e.g. Raspberry Pi 2 and 3), built with QEMU
- `arm64v8`/`arm64` - 64-bit ARM (e.g. Raspberry Pi 4), built with QEMU

This means that the standard image on Docker Hub will now work on Raspberry Pi the same as on standard x86_64 processors. I've tested and confirmed it works on my Raspberry Pi 3B+.

If you wish to build it yourself, you should still use the main Dockerfile in the root of the repository. The Dockerfiles in the `docker` directory are meant for use with Docker Hub.
