### ISSUE TITLE
Add an actual favicon.ico

### ISSUE THREAD

**Issue by licaon-kter** [bilde2910/Hauk#68]
...so it stops spamming my logs with an error. :)

Yes, the .png/.svg ones appear just fine but I guess the browser (?) insists on trying to get the .ico one too. :(

**Comment by bilde2910** [comment]
Added this now. Just out of curiosity, which browser does this happen with?

**Comment by licaon-kter** [comment]
Firefox 70

**Comment by licaon-kter** [comment]
300Kb? Oh...can you make it smaller? It's as big as the whole hauk/ web folder :(

**Comment by bilde2910** [comment]
Oh wow, didn't notice it was so big, actually. Using Firefox Developer 72.0b3 I cannot reproduce this issue. Could you copy the entry from your error log and/or paste a screenshot here from the network tab in the developer console (F12) after doing a hard reload (Ctrl+Shift+R or Ctrl+F5)? You may cover or blur out your domain name from the screenshot.

**Comment by bilde2910** [comment]
Apparently the reason the icon is so big is that [ICO files are not compressed](https://stackoverflow.com/a/31395706). Typically the file can be compressed by the web server using gzip before it's sent to the browser. This reduces the size dramatically:

```sh
[user@host frontend]$ cat favicon.ico | wc -c
308898
[user@host frontend]$ cat favicon.ico | gzip -c | wc -c
35488
```

**Comment by bilde2910** [comment]
Just removed the 256x256, 192x192 and 96x96 sizes from the icon. It's now just shy of 100 KB.

**Comment by licaon-kter** [comment]
I can't actually repro anymore, sorry for the noise, maybe you could reverse it.

I have the entries in the log from earlier, yet 4 browsers now can't trigger it with HEAD (remove .ico just to force them) or using a previous commit.

:(

**Comment by bilde2910** [comment]
Don't worry. And, it's strange. It could be bots, of course. I know that some older Internet Explorer versions don't play well with modern favicon specs, but those browsers should be old enough that the Hauk frontend wouldn't work anyway. If it happens again, you can check the user-agent in the access logs (if you log those) and it might give a clue as to who/what it is.

Reversing the favicon commit then as it does take some space unnecessarily :-)
