### ISSUE TITLE
Disable encryption key for group shares

### ISSUE THREAD

**Issue by licaon-kter** [bilde2910/Hauk#71]
...instead of just showing an error.

Right now I need to delete my encryption key while you could just disable the field and re-enable it (and keep my password if I checked the box) when I'm not sharing in a group.

1.5.1 F-Droid

**Comment by bilde2910** [comment]
That's a good idea. I'll make sure to add it so it's included in the next release.

**Comment by bilde2910** [comment]
Will be live in v1.5.2.
