### ISSUE TITLE
If no active link remove the text

### ISSUE THREAD

**Issue by licaon-kter** [bilde2910/Hauk#72]
...or change it to "No current active links".

**Comment by bilde2910** [comment]
Just to confirm, you're referring to this screen, right? The one that shows up when the link doesn't exist?

![image](https://user-images.githubusercontent.com/6617815/70392516-44c02300-19e1-11ea-8037-4fad359dacc7.png)

**Comment by licaon-kter** [comment]
No, in the app...scroll down...

**Comment by bilde2910** [comment]
Oh, yeah that makes more sense. I can add a label underneath that says something like

>You're not sharing your location right now. When you start a new location share, it will show up here"

... or something similar.

**Comment by licaon-kter** [comment]
I'd remove it or keep it as short as possible.

**Comment by bilde2910** [comment]
Actually, come to think of it, I could just remove it entirely and put it in its own window. Then on the red "Hauk" title bar, I can create a button on the far right that says e.g. "1 active link", you can click on it and it opens a window with the list of active links. Would that work?

**Comment by licaon-kter** [comment]
This small text can be tackled here, other stuff in https://github.com/bilde2910/Hauk/issues/74

**Comment by bilde2910** [comment]
I did the initially suggested fix for this and just rephrased the header label when there are no links active. Moving them to a separate page is complicated and not really needed right now.
