### ISSUE TITLE
Add Tor support

### ISSUE THREAD

**Issue by licaon-kter** [bilde2910/Hauk#75]
Right now you can either have the endpoint output revealing that it's Hauk _(info leak)_ or [block it unless the path is correct](https://github.com/bilde2910/Hauk/issues/31#issuecomment-531394782) _(why does anyone connect to this broken path every 30seconds?)_.

So, using https://gitlab.com/guardianproject/NetCipher/ you could have a setting for "**Use Tor**" that brings:
* HTTP proxy connection to 8118 _(enter via Tor, access clearnet via some exit node)_
* support for Tor Hidden Services, aka access the server via an .onion address _(never leave the Tor network)_

**Comment by bilde2910** [comment]
This is a really good idea. Running this on Tor is not something I even considered, but it makes a lot of sense. If you're willing to set Hauk up as a hidden service, then that could be accomplished with such a setup. I'll definitely be adding support for this, thanks for the great suggestion!

**Comment by licaon-kter** [comment]
Having a hidden service allows one to skip all the proxying, firewalling and having any port exposed.

**Comment by bilde2910** [comment]
Proxy support (HTTP and SOCKS 4/5) is now available in settings. If Orbot is downloaded and running, you can use Tor with Hauk by setting proxy host to `localhost` and port to 8118 (for HTTP) or 9050 (for SOCKS). This will be documented on the wiki.

**Comment by licaon-kter** [comment]
Two notes:
* allow a longer timeout for the connection, it takes longer at least at first start and when using .onion address
* allow invalid certificates for .onion addresses, one of the points of a Tor Hidden Address is DNS/CA cartels independence _(you can get a certificate for .onion but it costs money; also if you want a "hidden" service there's no point in "asking for permission from a CA entity")_

**Comment by bilde2910** [comment]
>allow a longer timeout for the connection, it takes longer at least at first start and when using .onion address

That's a good point. Default is 10 seconds, but I can make it configurable.

>allow invalid certificates for .onion addresses,

.onion is actually one of those rare cases where HTTPS is redundant. [Tor inherently provides encryption](https://cabforum.org/pipermail/public/2014-October/004214.html) as part of its protocol (the address is a hash of the hidden service's public key). I can try to add it as an option in settings.

**Comment by licaon-kter** [comment]
@bilde2910 I know, whatever you want it described the issue still stands, you need to allow the connection.

**Comment by bilde2910** [comment]
The alternative I propose is to use plain-text HTTP over encrypted Tor for the connection, i.e. don't use HTTPS in this case. That said, it's not a security *risk* to enable HTTPS for Tor, so I can add it as an option if I manage to implement it.

**Comment by bilde2910** [comment]
The problem is that if I disable certificate validation, it's essentially the same as using plain-text HTTP anyway. Sure it's encrypted at another layer, but you can't verify that the encryption in question is yours or if it's a certificate belonging to an attacker (if we look aside from the fact that Tor prevents that from happening). Another option would be to specifically add the root CA for your custom .onion certificate to your device, but even that isn't a good idea (more info in #55 and FAQ).

**Comment by licaon-kter** [comment]
The Tor connection gets routed to the same port as the other stuff hosted, hence 443, so Hauk needs to handle a cert.

**Comment by licaon-kter** [comment]
I don't have a cert for .onion, see OP
