### ISSUE TITLE
If offline show last online timestamp

### ISSUE THREAD

**Issue by licaon-kter** [bilde2910/Hauk#76]
..."offline since XXXX" or "offline for the last XXXX sec/min"

**Comment by bilde2910** [comment]
That's an interesting point. I'll have to figure out a way to integrate this into the web UI cleanly. I'll do some research and come back with screenshots or samples here.

**Comment by licaon-kter** [comment]
On top, near the clock maybe.

**Comment by bilde2910** [comment]
Problem is that there can be multiple people on a map at a time. One may be offline while another is still live. The red "Offline" that replaces the timer is an indicator that the map viewer is offline rather than the people sharing their locations.

**Comment by licaon-kter** [comment]
Oh, I didn't test multiple users yet.

**Comment by bilde2910** [comment]
Maybe something like this would work?

![image](https://user-images.githubusercontent.com/6617815/70430563-5f46da80-1a7b-11ea-9aaa-7d4468f4be89.png)

**Comment by licaon-kter** [comment]
Nice, though it won't be an arrow I guess?

**Comment by bilde2910** [comment]
It would be a circle that indicates no movement. The arrow is just there because of the GPS emulator I'm using to not disclose my location here. :-)

**Comment by bilde2910** [comment]
This is live; you can pull the latest version from Docker Hub in about 20 minutes or so.

**Comment by licaon-kter** [comment]
Just updated, not Docker, interior setting (so no GPS location on start), app says green "Location sharing active!" but GPS Test shows no lock (I guess same as #80).

Anyway, I get the circle and the OFFLINE, but no time. I guess it's because it didn't actually get a "last lock time"?

**Comment by bilde2910** [comment]
If you get the green "Location service active" then that means that the app has found a GPS fix. That said, it might not be continuously receiving them any more.

The "Offline" text actually isn't in the code any more. Could you try to clear cache in your browser/any caching providers (CloudFlare etc.) and see if that helps?

**Comment by licaon-kter** [comment]
Ok, works now after several forced reloads. Thanks

**Comment by licaon-kter** [comment]
Built app from HEAD too, noticed that it mostly says "2min ago", is this some rounding error?

I've [disconnected](https://github.com/bilde2910/Hauk/issues/85) the internet connections and appears to work ok, eg. 10 min have passed and now says 10 mins.

But online again, still "2min ago"...

**Comment by bilde2910** [comment]
The timestamp of the last received data is fetched from the app and sent to the browser, where the browser compares to its local time. Can you confirm that both devices' clocks run in sync?

**Comment by licaon-kter** [comment]
Devices meaning Android and/or server and/or browser?

**Comment by licaon-kter** [comment]
Another odd thing, checking the other [problematic share](https://github.com/bilde2910/Hauk/issues/105) in the browser, while indoors w/o a lock, the text always said "2h ago", now I can guess where these 2h come from _(server on UTC, client on local timezone)_, but while it had the GPS lock earlier, everything was ok _(time wise at least)_.

**Comment by bilde2910** [comment]
Both the app, frontend and backend all use Unix timestamps, so timezones won't be an issue. The "2h ago" would stem from there actually not being any updates for the past 2 hours received by the server.

**Comment by licaon-kter** [comment]
Actually thinking again, 2h might just be a the round off, eg. 2h55m will still be 2h, right? I'm not sure I was there >3 h.

Will have to retest somehow...

**Comment by bilde2910** [comment]
>2h55m will still be 2h, right?

Yes, it rounds down. 2h55m will still show as 2h. It switches to 3h once it reaches 3h00m.
