### ISSUE TITLE
Ask user if they really want to STOP sharing

### ISSUE THREAD

**Issue by licaon-kter** [bilde2910/Hauk#78]
...as maybe the button was touched by mistake.

**Comment by bilde2910** [comment]
Good idea. Will add this with an option to turn it off for a settings entry in #74

**Comment by bilde2910** [comment]
Added a prompt that shows by default, with an option to dismiss forever.

**Comment by licaon-kter** [comment]
Do apply this to the list of active shares below. ;)

**Comment by bilde2910** [comment]
Oh, forgot about those! Will add.

**Comment by bilde2910** [comment]
Added for the share list as well :-)

**Comment by licaon-kter** [comment]
Thaks

**Comment by licaon-kter** [comment]
Please reopen, stopping from notification does not respect the setting, there's no confirmation dialogue.

**Comment by bilde2910** [comment]
I will look into how this can be done feasibly. How easy is it to accidentally stop sharing from the notification, given that you have to swipe down to access it in the first place?
