### ISSUE TITLE
Remove the password-warning

### ISSUE THREAD

**Issue by natrius** [bilde2910/Hauk#8]
Or at least change the wording, because that is not a password the user with the app is going to choose, the server-admin chooses it. So it is completely his responsibility, not the one of my friend because he can not do anything about it :D

**Comment by bilde2910** [comment]
The idea was that the person setting up the server is likely the same person as the one primarily using the app. But you've got a point - I can move this warning to the configuration instead; then it will be the server admin's responsibility to use a strong password.

**Comment by bilde2910** [comment]
This will be live in v1.0.2.

**Comment by bilde2910** [comment]
This is now live in v1.1. It may take a couple of days for F-Droid to build this new version.
