### ISSUE TITLE
Stopping the last link should stop global share

### ISSUE THREAD

**Issue by licaon-kter** [bilde2910/Hauk#82]
1.5.1 F-Droid

Share 1 link only, press its stop button, see that the "stop sharing [time]" button above still counts time.

**Comment by bilde2910** [comment]
That's a good idea. Will consider this a bug as the expected experience for the user when clicking this button is that the session ends completely.

**Comment by licaon-kter** [comment]
And the notification :)

**Comment by bilde2910** [comment]
Will be live in v1.5.2.
