### ISSUE TITLE
Don't leak passwords in Android logs

### ISSUE THREAD

**Issue by licaon-kter** [bilde2910/Hauk#83]
> info.varden.hauk: .utils.PreferenceManager.set(PreferenceManager.java:42): Setting preference Preference<String+Encrypted>{key=cryptPassword,default=}, value=MYSERVERPASSWORDINPLAINTEXT

and
> I info.varden.hauk: .caching.ResumableSessions.setSessionResumable(ResumableSessions.java:80): Setting session Session{serverURL=https://domain.tld/,backendVersion=1.5,sessionID=xxxxxxxxxxxxxxxxxxxxxxxxx,expiry=15759074xxxxx,interval=5,e2eParams=KeyDerivable{password=MYE2ESHAREPASSWORDINPLAINTEXT,salt=0xxxxxxxxxxxxxxxxxxxxxxxxxxxx}} resumable

**Comment by bilde2910** [comment]
That's a very good point. I'll remove the password from the logs. The salt is randomly generated and not considered secret.

**Comment by bilde2910** [comment]
Fixed in upcoming v1.5.2.
