### ISSUE TITLE
In app, add info if server is unreachable

### ISSUE THREAD

**Issue by licaon-kter** [bilde2910/Hauk#85]
...eg. Under "Location sharing/Waiting for GNSS" add "Server unreachable" if no connection or server down.

I just disconnected both Wi-Fi and mobile data to test [offline timestamp](https://github.com/bilde2910/Hauk/issues/76). ;)

**Comment by bilde2910** [comment]
Good idea, will get to work on this.

**Comment by bilde2910** [comment]
This will be live in v1.5.2.
