### ISSUE TITLE
Browser expired time shows as NaN:NaN

### ISSUE THREAD

**Issue by licaon-kter** [bilde2910/Hauk#88]
Server/app HEAD (58e5ac9414610fc3ee5e7b9366334a6858b89655)

**Comment by bilde2910** [comment]
Did you remember to update the backend to HEAD as well? I was able to reproduce this only when the frontend was updated, but not the backend. You can check in developer tools if this field exists. If it does not, your backend is not up to date.

![image](https://user-images.githubusercontent.com/6617815/70518059-f96d5800-1b39-11ea-9d7d-0d7f182ea66b.png)

**Comment by licaon-kter** [comment]
Indeed I don't have that.

I've copied the files again and now it's fixed. Thanks
