### ISSUE TITLE
Support SASL user auth with memcached

### ISSUE THREAD

**Issue by BrookeDot** [bilde2910/Hauk#9]
Howdy, 

I use `memcached` with Simple Authentication and Security Layer (SASL) meaning to connect to the sever a user and password must be passed to the memcache options.  I have done this in my local install by modifying the `memcached` wrapper with the required options, ie:

```
    function __construct($host, $port) {
        $this->memcache = new Memcached();
        $this->memcache->setOption( Memcached::OPT_BINARY_PROTOCOL, true );
        $this->memcache->setSaslAuthData( “USER”, “PASSWORD” );
        $this->memcache->addServer(CONFIG["memcached_host"], CONFIG["memcached_port"])
                   or die ("Server could not connect to memcached!\n");
    }
```

What I'm hoping is to find a way to have this supported via the config.php file. May be able to do something like addin `memcached_binary_protocol`  and`memcached_setSaslAuthData` to the options then check for them conditionally. I'm just not sure if this is helpful for others or if a more generic way of adding additional options would be better.

Interested to hear your thoughts on this.

**Comment by bilde2910** [comment]
This looks like a good idea. Haven't used memcached before, so I don't know its full capabilities yet, but this seems like a must-have. I'll see if I can get this included in the next release.

Will probably result in adding `memcached_protocol`, `memcached_use_sasl`, `memcached_sasl_user` and `memcached_sasl_password` settings.

Thanks for the suggestion!

**Comment by BrookeDot** [comment]
I'm also pretty new to memcached just set it up a few months ago with SASL based on the [DigitalOcean tutorial](https://www.digitalocean.com/community/tutorials/how-to-install-and-secure-memcached-on-ubuntu-16-04). There may be other options that people will want to add so perhaps more generic option in the future may be needed. However, your suggested settings variables for SASL make a lot of sense for now. It would be great to see this in the next version.

**Comment by bilde2910** [comment]
This will be supported in the next release :+1:
