### ISSUE TITLE
HTPASSWD not working

### ISSUE THREAD

**Issue by iMartyn** [bilde2910/Hauk#90]
Running the docker image (1.2 tag) in my k8s cluster, config.php and users.htpasswd mapped in via configmap and secret.

Not that it should make any difference but the users.htpasswd is created `root:root -rw-r--r--`.  Unless the app is trying to open it read-write, that's valid.

Using the companion app when I try to create a share I get the following message : 

```
Server error
<br /> <b>Warning</b>: Use of undefined constant HTPASSWD - assumed 'HTPASSWD' (this will throw an Error in a future version of PHP) in <b>/etc/hauk/config.php</b> on line <b>1</b><br /> <br /> <b>Warning</b>: Use of undefined constant LINK_4_PLUS_4_UPPER_CASE - assumed "LINK_4_PLUS_4_UPPER_CASE' (this will throw an Error in a future version of PHP) in <b>/etc/hauk/config.php</b> on line <b>1</b><br />
<br /> <b>Warning</b>: Cannot modify header information - headers already sent by (output started at /etc/hauk/config.php:1) in <b>/var/www/html/api/create.php</b> on line <b>7</ b><br /> Incorrect password!
OK
```
Leaving aside the fact that it's returning a 200 for what should be a 403, it appears the config import doesn't appear to be pulling in the constants from `inc.php`

It's been too long since I've worked with php, but something rings a bell about include vs require for constants, but it's a very faint bell.

Interestingly, setting `auth_method` to `1` and entering a valid or an invalid user validates against the shared password. :(

It would be nice to have some logs other than the apache logs as well, but nothing in /var/log/ is useful here.

Config attached prior to changing the shared passwd.
![Screenshot_20191210_152336_info varden hauk](https://user-images.githubusercontent.com/962908/70539630-42d29d00-1b64-11ea-9357-46e4171461af.jpg)
[config.php.txt](https://github.com/bilde2910/Hauk/files/3945418/config.php.txt)

**Comment by bilde2910** [comment]
1.2 is an old tag - username and password support was added in 1.4. You should update to a newer tag (latest tagged release is 1.5.1) or preferably the `latest` tag so it stays up to date without having to change the tag again later.

**Comment by iMartyn** [comment]
I never use :latest, that's considered bad practice these days, but yep, I misremembered the latest tag clearly.  My bad!  Might be worth putting a comment above the sample in the `README.md` to point out to change the tag if you're not running from master.  I might have spotted the version mismatch then (might not have, but if it saves issues like this one being reported, that'd be good, right?)

**Comment by bilde2910** [comment]
Yeah, better documentation in the README sounds like a good idea. I can also create a `stable` tag that is updated on every new release, but not on every new commit like `latest` is. Maybe that can help too, ensuring that the image is always up to date, but not necessarily at the bleeding edge level.

**Comment by bilde2910** [comment]
Tag 1.5.2 is now being built along with the new tag `stable-1.x` which will update every time there is a new release on v1.x.

![image](https://user-images.githubusercontent.com/6617815/70546514-bc23bd00-1b6f-11ea-8cde-773c5faf0c60.png)

When the builds are completed, I'll update the README with more information about tags.

**Comment by bilde2910** [comment]
README is now updated, explaining all the tags. :-)
