### ISSUE TITLE
Don't allow O / 0 in the IDs

### ISSUE THREAD

**Issue by iMartyn** [bilde2910/Hauk#91]
I know the mixed case scheme doesn't use `l` and `I` but the first ever link I got contained an `O` and an `0`!

It'd be nice to stop that from happening too.

**Comment by bilde2910** [comment]
That's a pretty good point, actually. I'll make sure to change the dictionary space so it can't contain O or 0. This does reduce the number of possible combinations by about 37%, but still maintains long enough time to bruteforce on the default setting (~28 years @ 1000/sec) that it shouldn't matter significantly for security in practice. I'll get this included in v1.6.

**Comment by bilde2910** [comment]
Removed 0 and O from the character pool for upper- and mixed-case IDs.
