### ISSUE TITLE
Investigate if a Kalman filter is useful

### ISSUE THREAD

**Issue by licaon-kter** [bilde2910/Hauk#94]
Ref https://en.wikipedia.org/wiki/Kalman_filter 

Eg. To smooth out jittery or sudden value changes

**Comment by RuralYak** [comment]
@licaon-kter any explanations here?

**Comment by bilde2910** [comment]
I'm not familiar with this algorithm. Could you elaborate a bit on the problem/use case that this would benefit?

**Comment by licaon-kter** [comment]
Not sure if needed really (in theory GPS data is already Kalman filtered to a degree).

**Comment by bilde2910** [comment]
Makes sense. Will tag as `wontfix` for now. The Android geolocation provider seems to be quite stable and accurate, and accuracy does increase as more fixes are obtained already.
