### ISSUE TITLE
Split session expired and pressed button to stop messages

### ISSUE THREAD

**Issue by licaon-kter** [bilde2910/Hauk#95]
...in the current setup you get the same "Your location share has expired" message, which is rather odd to see when one presses the button to "Stop sharing"

I'd guess [here](https://github.com/bilde2910/Hauk/blob/699404006d32b63c6814d7fdf40804ec3eebaf6f/android/app/src/main/java/info/varden/hauk/ui/StopSharingUICallback.java#L54) and [here](https://github.com/bilde2910/Hauk/blob/e50d3159e54544be8d9217f994cd8b1099493a9a/android/app/src/main/java/info/varden/hauk/global/BroadcastSessionManager.java#L44)

"Your location share has expired"
vs
"You have stopped sharing the location"

**Comment by bilde2910** [comment]
Would "Your location share has ended" work?

**Comment by licaon-kter** [comment]
Yes, whatever you want it phrased. :)

**Comment by bilde2910** [comment]
Changed "expired" to "ended". "Expired" only works if if the share expired by itself; "ended" also works if the user stops it manually.
