### ISSUE TITLE
Rephrase from "Encrypted"

### ISSUE THREAD

**Issue by licaon-kter** [bilde2910/Hauk#96]
...to "Password protected", as that's the right description of its function anyway.

**Comment by bilde2910** [comment]
In which contexts? All contexts in which "encrypt" shows up?

Password protected shares are actually encrypted using AES-256 so the phrasing is accurate; rephrasing it would depend on whether that's a good idea from a UX perspective.

**Comment by bilde2910** [comment]
You know, come to think of it, you have a point. It's better to describe the result than the process. Particularly for less tech savvy end users, it's better to tell them that they have to enter a password because it's password protected, rather than trying to make them understand encryption. Everyone knows what a password is anyway. I'll see if I can make this change tomorrow.

**Comment by licaon-kter** [comment]
All the passwords are encrypted somewhere (we don't care, we hope they are), but the actual sharing link is just "password protected".

**Comment by licaon-kter** [comment]
Also push these changes to the translation portal. Thanks

**Comment by bilde2910** [comment]
The changes are pushed to the portal already. The strings "Enable end-to-end encryption" and "Disable end-to-end encryption" are kept as-is as they are the helper text for the "Password protect share" option (which was changed).

![image](https://user-images.githubusercontent.com/6617815/70704759-f194eb80-1cd2-11ea-8ae1-318e7b9379fb.png)

**Comment by licaon-kter** [comment]
"end-to-end encryption" in the lines of https://en.wikipedia.org/wiki/End-to-end_encryption

So you say that the server doesn't know the actual location and stores the coords encrypted with the password? I didn't look in the code

**Comment by bilde2910** [comment]
That is correct. The data is [encrypted here](https://github.com/bilde2910/Hauk/blob/master/android/app/src/main/java/info/varden/hauk/http/LocationUpdatePacket.java#L60-L73) in the app and [decrypted by the frontend](https://github.com/bilde2910/Hauk/blob/master/frontend/main.js#L412-L519). The backend has no idea what the data actually is and just has to pass it though [without performing any validation](https://github.com/bilde2910/Hauk/blob/master/backend-php/api/post.php#L43) or processing it in any way, as it doesn't have the key.

**Comment by haadr** [comment]
> That is correct. The data is [encrypted here](https://github.com/bilde2910/Hauk/blob/master/android/app/src/main/java/info/varden/hauk/http/LocationUpdatePacket.java#L60-L73) in the app and [decrypted by the frontend](https://github.com/bilde2910/Hauk/blob/master/frontend/main.js#L412-L519). The backend has no idea what the data actually is and just has to pass it though [without performing any validation](https://github.com/bilde2910/Hauk/blob/master/backend-php/api/post.php#L43) or processing it in any way, as it doesn't have the key.

This is great to hear! I've been reading about Hauk before possibly giving it a try, and I saw on the screenshot that there's a reference to "end-to-end encryption", but I couldn't find anything about it in the FAQ.

Is this documented anywhere? If not, maybe it would be good to document it as it's a "killer feature" for many :)

**Comment by bilde2910** [comment]
> This is great to hear! I've been reading about Hauk before possibly giving it a try, and I saw on the screenshot that there's a reference to "end-to-end encryption", but I couldn't find anything about it in the FAQ.
> 
> Is this documented anywhere? If not, maybe it would be good to document it as it's a "killer feature" for many :)

That's a good idea, actually. Didn't think about adding it to the FAQ, but I'll make sure to get that done soon.
