### ISSUE TITLE
Translation portal - Add Romanian

### ISSUE THREAD

**Issue by licaon-kter** [bilde2910/Hauk#97]

**Comment by bilde2910** [comment]
The translation portal is self-serve. Sign in with GitHub or GitLab first, then head to the [project page](https://traduki.varden.info/projects/hauk/) and you'll see three components. Click into each of the components and you'll see the list of languages, and be able to start a new translation, for each of them :-)

**Comment by licaon-kter** [comment]
I'm dumb... I never entered in the component, I was expecting the button outside.

Thanks

**Comment by licaon-kter** [comment]
Done.

**Comment by bilde2910** [comment]
Awesome, thanks! Just pushed your submissions to the repo. Will make sure to give you credits in the README as well :-)

**Comment by licaon-kter** [comment]
Could you remove the empty strings like img_alt_logo and app_name? The APK has no name :))

**Comment by bilde2910** [comment]
Done

**Comment by licaon-kter** [comment]
Don't forget to push to Weblate too. Thanks

**Comment by licaon-kter** [comment]
This message is not available for translation
```
JavaScript disabled

Hauk fundamentally requires JavaScript to function. Please enable JavaScript and reload the page to view the Hauk map.
```

**Comment by bilde2910** [comment]
That's because JavaScript is used to populate translations onto the frontend. I can't update that text to that of another language unless JavaScript is enabled.

**Comment by licaon-kter** [comment]
Chicken and egg :) :)
